import { defineComponent } from "vue";
import s from "./emoji-select.module.scss";

export const EmojiSelect = defineComponent({
  setup: () => {
    return () => (
      <div class={s.wrapper}>
        <nav>
          <span>表情</span>
          <span>手势</span>
          <span>职业</span>
          <span>衣服</span>
          <span>动物</span>
          <span>自然</span>
          <span>食物</span>
          <span>运动</span>
          <span>运动</span>
          <span>运动</span>
          <span>运动</span>
        </nav>
        <ol>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
          <li>😊</li>
        </ol>
      </div>
    )
  }
})